---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)

library(p8105.datasets)

data(rest_inspec)
data(instacart)
```

```{r}
data("instacart")

instacart_cat = 
  instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart_cat |> 
  plot_ly(x= ~aisle, y= ~n, color= ~aisle,
          type ='bar', made= 'markers', alpha=0.5)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart |> 
  filter(aisle %in% c('baking ingredients', 'refrigerated', 'fresh vegetables') )|>
  group_by(aisle) |> 
  count(product_name) |> 
  mutate(rank = min_rank(desc(n))) |> 
  filter(rank < 10) |> 
  mutate(product_name= fct_reorder (product_name, rank)) |> 
  plot_ly(x= ~product_name, y = ~n, color = ~product_name, type = "scatter", colors = "viridis")
```

### Chart C

```{r}
instacart |>
  filter(product_name %in% c ("Bulgarian Yogurt","	
Cucumber Kirby","Bag of Organic Bananas","Spring Water","Asparagus","Shelled Pistachios")) |>
  group_by(product_name, order_dow) |>
  summarize(mean_hour = mean(order_hour_of_day))|>
  plot_ly( y =~mean_hour, color = ~product_name,type = "box", colors = "viridis")
```

